import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./app.scss";
import Link from "next/link";
import { ToastComponent } from "@/components/toast.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen w-screen overflow-hidden">
          <div className="flex-1 flex flex-col ">
            <nav className="h-14 flex items-center px-4 bg-blue-900 gap-4">
              <div className="flex gap-4">
                <Link href={"/"}>
                  <h1 className=" text-white">Tech Market - Inicio</h1>
                </Link>
              </div>
            </nav>
            <div className="flex-1 overflow-auto bg-background-100 p-4 h-full">
              {children}
              <ToastComponent></ToastComponent>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
