global using Dapper;
global using Microsoft.Extensions.Options;
global using System.Data.Common;
global using Tech.Market.API.Contracts;
global using Tech.Market.API.Options;
global using Tech.Market.API.Repositories;
global using Microsoft.AspNetCore.Mvc;
global using System.Linq;
global using System.Text;
global using static Dapper.SqlMapper;
global using Microsoft.Data.SqlClient;
global using Tech.Market.Core.Entities;